USE []
GO
/****** Object:  Index [IDX__AWARDS__AWARD_TYPE]    Script Date: 06/09/2010 16:58:59 ******/
CREATE NONCLUSTERED INDEX [IDX__AWARDS__AWARD_TYPE] ON [dbo].[awards] 
(
	[award_type] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]