USE []
GO
/****** Object:  Index [IDX__AWARD_TEST__AWARD_TYPE]    Script Date: 06/09/2010 16:57:30 ******/
CREATE NONCLUSTERED INDEX [IDX__AWARD_TEST__AWARD_TYPE] ON [dbo].[award_testimonials] 
(
	[award_type] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]