USE []
GO
/****** Object:  Index [IDX__IMAGE_LIBRARY__ASSET_TYPE]    Script Date: 06/09/2010 17:00:46 ******/
CREATE NONCLUSTERED INDEX [IDX__IMAGE_LIBRARY__ASSET_TYPE] ON [dbo].[image_library] 
(
	[asset_type] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]