USE []
GO
/****** Object:  Index [IDX__PRODUCTS__DISCONTINUED]    Script Date: 06/09/2010 17:03:24 ******/
CREATE NONCLUSTERED INDEX [IDX__PRODUCTS__DISCONTINUED] ON [dbo].[products] 
(
	[discontinued] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]