USE []
GO
/****** Object:  Index [IDX__PRODUCTS__PRODUCT_CATEGORY]    Script Date: 06/09/2010 17:04:03 ******/
CREATE NONCLUSTERED INDEX [IDX__PRODUCTS__PRODUCT_CATEGORY] ON [dbo].[products] 
(
	[product_category] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]