USE []
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[DBO].[V_WWA_DEPLOYMENT_GATE_LATEST]'))
DROP VIEW [DBO].[V_WWA_DEPLOYMENT_GATE_LATEST]
GO
CREATE VIEW [DBO].[V_WWA_DEPLOYMENT_GATE_LATEST] AS
SELECT DEPLOYMENT_DATE
      ,PROD_DEV_CODE
      ,LOCAL_PRODUCT
      ,MIGRATED
      ,DEPLOY
      ,STATUS
      ,SPENT
FROM  [DBO].[WWA_DEPLOYMENT_GATE]
WHERE DEPLOYMENT_DATE = (SELECT MAX(DEPLOYMENT_DATE) FROM WWA_DEPLOYMENT_GATE)
AND   SPENT = 0;
GO
SET ANSI_PADDING OFF