package com.interwoven.teamsite.nikon.hibernate.beans;

// Generated 18-Oct-2009 14:29:28 by Hibernate Tools 3.2.4.GA

/**
 * Award generated by hbm2java
 */
public class Award implements java.io.Serializable {

	private String id;
	private String awardId;
	private String nikonLocale;
	private String path;

	public Award() {
	}

	public Award(String id) {
		this.id = id;
	}

	public Award(String id, String awardId, String nikonLocale, String path) {
		this.id = id;
		this.awardId = awardId;
		this.nikonLocale = nikonLocale;
		this.path = path;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getAwardId() {
		return this.awardId;
	}

	public void setAwardId(String awardId) {
		this.awardId = awardId;
	}

	public String getNikonLocale() {
		return this.nikonLocale;
	}

	public void setNikonLocale(String nikonLocale) {
		this.nikonLocale = nikonLocale;
	}

	public String getPath() {
		return this.path;
	}

	public void setPath(String path) {
		this.path = path;
	}

}
