package com.interwoven.teamsite.nikon.hibernate.beans;

// Generated 21-Apr-2009 22:18:07 by Hibernate Tools 3.2.2.GA

import java.util.Date;

/**
 * NewsArticle generated by hbm2java
 */
public class NewsArticle implements java.io.Serializable {

	private String id;
	private String nikonLocale;
	private boolean relatesToProducts;
	private String path;
	private boolean keepOnPage;
	private Date wwaDate;
	private short sortOrder;

	public NewsArticle() {
	}

	public NewsArticle(String id) {
		this.id = id;
	}

	public NewsArticle(String id, String nikonLocale,
			boolean relatesToProducts, String path, boolean keepOnPage,
			Date wwaDate, short sortOrder) {
		this.id = id;
		this.nikonLocale = nikonLocale;
		this.relatesToProducts = relatesToProducts;
		this.path = path;
		this.keepOnPage = keepOnPage;
		this.wwaDate = wwaDate;
		this.sortOrder = sortOrder;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getNikonLocale() {
		return this.nikonLocale;
	}

	public void setNikonLocale(String nikonLocale) {
		this.nikonLocale = nikonLocale;
	}

	public boolean isRelatesToProducts() {
		return this.relatesToProducts;
	}

	public void setRelatesToProducts(boolean relatesToProducts) {
		this.relatesToProducts = relatesToProducts;
	}

	public String getPath() {
		return this.path;
	}

	public void setPath(String path) {
		this.path = path;
	}

	public boolean isKeepOnPage() {
		return this.keepOnPage;
	}

	public void setKeepOnPage(boolean keepOnPage) {
		this.keepOnPage = keepOnPage;
	}

	public Date getWwaDate() {
		return this.wwaDate;
	}

	public void setWwaDate(Date wwaDate) {
		this.wwaDate = wwaDate;
	}

	public short getSortOrder() {
		return this.sortOrder;
	}

	public void setSortOrder(short sortOrder) {
		this.sortOrder = sortOrder;
	}

}
