package com.interwoven.teamsite.nikon.hibernate.beans;

// Generated 18-Oct-2009 14:29:28 by Hibernate Tools 3.2.4.GA

import java.util.Date;

/**
 * PressLibrary generated by hbm2java
 */
public class PressLibrary implements java.io.Serializable {

	private String id;
	private String nikonLocale;
	private Date wwaDate;
	private String path;
	private boolean localAsset;
	private String localAssetLocale;
	private boolean localeAssetOptOut;
	private String localeAssetOptOutLocale;
	private String pressLibraryCategory;
	private String navCat1;
	private String navCat2;
	private String navCat3;
	private String navName;
	private String relatedProductLocaleShortName;
	private String relatedProductShortName;

	public PressLibrary() {
	}

	public PressLibrary(String id, Date wwaDate) {
		this.id = id;
		this.wwaDate = wwaDate;
	}

	public PressLibrary(String id, String nikonLocale, Date wwaDate,
			String path, String localAssetLocale,
			String localeAssetOptOutLocale, String pressLibraryCategory,
			String navCat1, String navCat2, String navCat3, String navName, 
			String relatedProductLocaleShortName, String relatedProductShortName) {
		this.id = id;
		this.nikonLocale = nikonLocale;
		this.wwaDate = wwaDate;
		this.path = path;
		this.localAssetLocale = localAssetLocale;
		this.localeAssetOptOutLocale = localeAssetOptOutLocale;
		this.pressLibraryCategory = pressLibraryCategory;
		this.navCat1 = navCat1;
		this.navCat2 = navCat2;
		this.navCat3 = navCat3;
		this.navName = navName;
		this.relatedProductLocaleShortName = relatedProductLocaleShortName;
		this.relatedProductShortName = relatedProductShortName;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getNikonLocale() {
		return this.nikonLocale;
	}

	public void setNikonLocale(String nikonLocale) {
		this.nikonLocale = nikonLocale;
	}

	public Date getWwaDate() {
		return this.wwaDate;
	}

	public void setWwaDate(Date wwaDate) {
		this.wwaDate = wwaDate;
	}

	public String getPath() {
		return this.path;
	}

	public void setPath(String path) {
		this.path = path;
	}

	public boolean isLocalAsset() {
		return this.localAsset;
	}

	public void setLocalAsset(boolean localAsset) {
		this.localAsset = localAsset;
	}

	public String getLocalAssetLocale() {
		return this.localAssetLocale;
	}

	public void setLocalAssetLocale(String localAssetLocale) {
		this.localAssetLocale = localAssetLocale;
	}

	public boolean isLocaleAssetOptOut() {
		return this.localeAssetOptOut;
	}

	public void setLocaleAssetOptOut(boolean localeAssetOptOut) {
		this.localeAssetOptOut = localeAssetOptOut;
	}

	public String getLocaleAssetOptOutLocale() {
		return this.localeAssetOptOutLocale;
	}

	public void setLocaleAssetOptOutLocale(String localeAssetOptOutLocale) {
		this.localeAssetOptOutLocale = localeAssetOptOutLocale;
	}

	public String getPressLibraryCategory() {
		return this.pressLibraryCategory;
	}

	public void setPressLibraryCategory(String pressLibraryCategory) {
		this.pressLibraryCategory = pressLibraryCategory;
	}

	public String getNavCat1() {
		return this.navCat1;
	}

	public void setNavCat1(String navCat1) {
		this.navCat1 = navCat1;
	}

	public String getNavCat2() {
		return this.navCat2;
	}

	public void setNavCat2(String navCat2) {
		this.navCat2 = navCat2;
	}

	public String getNavCat3() {
		return this.navCat3;
	}

	public void setNavCat3(String navCat3) {
		this.navCat3 = navCat3;
	}

	public String getNavName() {
		return this.navName;
	}

	public void setNavName(String navName) {
		this.navName = navName;
	}

	public String getRelatedProductLocaleShortName() {
		return this.relatedProductLocaleShortName;
	}

	public void setRelatedProductLocaleShortName(String relatedProductLocaleShortName) {
		this.relatedProductLocaleShortName = relatedProductLocaleShortName;
	}	

	public String getRelatedProductShortName() {
		return this.relatedProductShortName;
	}

	public void setRelatedProductShortName(String relatedProductShortName) {
		this.relatedProductShortName = relatedProductShortName;
	}	
	
}
