package com.interwoven.teamsite.nikon.hibernate.beans;

// Generated 18-Oct-2009 14:29:28 by Hibernate Tools 3.2.4.GA

/**
 * Price generated by hbm2java
 */
public class Price implements java.io.Serializable {

	private String id;
	private String prodDevCode;
	private String nikonLocale;
	private String priceIncVat;
	private String currenyCode;
	private Product Product;

	public Price() {
	}

	public Price(String id, String prodDevCode, String nikonLocale,
			String priceIncVat, String currenyCode) {
		this.id = id;
		this.prodDevCode = prodDevCode;
		this.nikonLocale = nikonLocale;
		this.priceIncVat = priceIncVat;
		this.currenyCode = currenyCode;
	}

	public Price(String id, String prodDevCode, String nikonLocale,
			String priceIncVat, String currenyCode, Product Product) {
		this.id = id;
		this.prodDevCode = prodDevCode;
		this.nikonLocale = nikonLocale;
		this.priceIncVat = priceIncVat;
		this.currenyCode = currenyCode;
		this.Product = Product;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getProdDevCode() {
		return this.prodDevCode;
	}

	public void setProdDevCode(String prodDevCode) {
		this.prodDevCode = prodDevCode;
	}

	public String getNikonLocale() {
		return this.nikonLocale;
	}

	public void setNikonLocale(String nikonLocale) {
		this.nikonLocale = nikonLocale;
	}

	public String getPriceIncVat() {
		return this.priceIncVat;
	}

	public void setPriceIncVat(String priceIncVat) {
		this.priceIncVat = priceIncVat;
	}

	public String getCurrenyCode() {
		return this.currenyCode;
	}

	public void setCurrenyCode(String currenyCode) {
		this.currenyCode = currenyCode;
	}

	public Product getProduct() {
		return this.Product;
	}

	public void setProduct(Product Product) {
		this.Product = Product;
	}

}
