package com.interwoven.teamsite.nikon.hibernate.beans;

// Generated 18-Oct-2009 14:29:28 by Hibernate Tools 3.2.4.GA

/**
 * ProductLocaleOptOutPK generated by hbm2java
 */
public class ProductLocaleOptOutPK implements java.io.Serializable {

	private String id;
	private String prodId;
	private String localeOptOut;

	public ProductLocaleOptOutPK() {
	}

	public ProductLocaleOptOutPK(String id, String prodId, String localeOptOut) {
		this.id = id;
		this.prodId = prodId;
		this.localeOptOut = localeOptOut;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getProdId() {
		return this.prodId;
	}

	public void setProdId(String prodId) {
		this.prodId = prodId;
	}

	public String getLocaleOptOut() {
		return this.localeOptOut;
	}

	public void setLocaleOptOut(String localeOptOut) {
		this.localeOptOut = localeOptOut;
	}

}
