package com.interwoven.teamsite.nikon.hibernate.beans;

// Generated 18-Oct-2009 14:29:28 by Hibernate Tools 3.2.4.GA

/**
 * ProductLocaleOptOut generated by hbm2java
 */
public class ProductLocaleOptOut implements java.io.Serializable {

	private ProductLocaleOptOutPK id;
	private String prodId;
	private String localeOptOut;

	public ProductLocaleOptOut() {
	}

	public ProductLocaleOptOut(ProductLocaleOptOutPK id) {
		this.id = id;
	}

	public ProductLocaleOptOut(ProductLocaleOptOutPK id, String prodId,
			String localeOptOut) {
		this.id = id;
		this.prodId = prodId;
		this.localeOptOut = localeOptOut;
	}

	public ProductLocaleOptOutPK getId() {
		return this.id;
	}

	public void setId(ProductLocaleOptOutPK id) {
		this.id = id;
	}

	public String getProdId() {
		return this.prodId;
	}

	public void setProdId(String prodId) {
		this.prodId = prodId;
	}

	public String getLocaleOptOut() {
		return this.localeOptOut;
	}

	public void setLocaleOptOut(String localeOptOut) {
		this.localeOptOut = localeOptOut;
	}

}
