package com.interwoven.teamsite.nikon.hibernate.beans;

// Generated 18-Oct-2009 14:29:28 by Hibernate Tools 3.2.4.GA

/**
 * Product2AwardPK generated by hbm2java
 */
public class Product2AwardPK implements java.io.Serializable {

	private String id;
	private String prodProdId;
	private String awardTestId;

	public Product2AwardPK() {
	}

	public Product2AwardPK(String id, String prodProdId, String awardTestId) {
		this.id = id;
		this.prodProdId = prodProdId;
		this.awardTestId = awardTestId;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getProdProdId() {
		return this.prodProdId;
	}

	public void setProdProdId(String prodProdId) {
		this.prodProdId = prodProdId;
	}

	public String getAwardTestId() {
		return this.awardTestId;
	}

	public void setAwardTestId(String awardTestId) {
		this.awardTestId = awardTestId;
	}

}
