package com.interwoven.teamsite.nikon.hibernate.beans;

// Generated 11-Feb-2009 21:40:53 by Hibernate Tools 3.2.2.GA

/**
 * Product2ProductLocaleOptOutPK generated by hbm2java
 */
public class Product2ProductLocaleOptOutPK implements java.io.Serializable {

	private String id;
	private String prodId;
	private String localeOptOut;

	public Product2ProductLocaleOptOutPK() {
	}

	public Product2ProductLocaleOptOutPK(String id, String prodId,
			String localeOptOut) {
		this.id = id;
		this.prodId = prodId;
		this.localeOptOut = localeOptOut;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getProdId() {
		return this.prodId;
	}

	public void setProdId(String prodId) {
		this.prodId = prodId;
	}

	public String getLocaleOptOut() {
		return this.localeOptOut;
	}

	public void setLocaleOptOut(String localeOptOut) {
		this.localeOptOut = localeOptOut;
	}

}
