package com.interwoven.teamsite.nikon.hibernate.beans;

// Generated 25-Feb-2009 12:01:06 by Hibernate Tools 3.2.2.GA

/**
 * Product2AccessoryLocaleOptOutPK generated by hbm2java
 */
public class Product2AccessoryLocaleOptOutPK implements java.io.Serializable {

	private String id;
	private String prodId;
	private String localeOptOut;

	public Product2AccessoryLocaleOptOutPK() {
	}

	public Product2AccessoryLocaleOptOutPK(String id, String prodId,
			String localeOptOut) {
		this.id = id;
		this.prodId = prodId;
		this.localeOptOut = localeOptOut;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getProdId() {
		return this.prodId;
	}

	public void setProdId(String prodId) {
		this.prodId = prodId;
	}

	public String getLocaleOptOut() {
		return this.localeOptOut;
	}

	public void setLocaleOptOut(String localeOptOut) {
		this.localeOptOut = localeOptOut;
	}

}
