package com.interwoven.teamsite.nikon.hibernate.beans;

// Generated 11-Feb-2009 21:40:53 by Hibernate Tools 3.2.2.GA

/**
 * Product2ProductLocaleOptOut generated by hbm2java
 */
public class Product2ProductLocaleOptOut implements java.io.Serializable {

	private Product2ProductLocaleOptOutPK id;
	private String prodId;
	private String localeOptOut;

	public Product2ProductLocaleOptOut() {
	}

	public Product2ProductLocaleOptOut(Product2ProductLocaleOptOutPK id) {
		this.id = id;
	}

	public Product2ProductLocaleOptOut(Product2ProductLocaleOptOutPK id,
			String prodId, String localeOptOut) {
		this.id = id;
		this.prodId = prodId;
		this.localeOptOut = localeOptOut;
	}

	public Product2ProductLocaleOptOutPK getId() {
		return this.id;
	}

	public void setId(Product2ProductLocaleOptOutPK id) {
		this.id = id;
	}

	public String getProdId() {
		return this.prodId;
	}

	public void setProdId(String prodId) {
		this.prodId = prodId;
	}

	public String getLocaleOptOut() {
		return this.localeOptOut;
	}

	public void setLocaleOptOut(String localeOptOut) {
		this.localeOptOut = localeOptOut;
	}

}
