package com.interwoven.teamsite.nikon.hibernate.beans;

// Generated 25-Feb-2009 12:01:06 by Hibernate Tools 3.2.2.GA

/**
 * Product2AccessoryLocaleOptOut generated by hbm2java
 */
public class Product2AccessoryLocaleOptOut implements java.io.Serializable {

	private Product2AccessoryLocaleOptOutPK id;
	private String prodId;
	private String localeOptOut;

	public Product2AccessoryLocaleOptOut() {
	}

	public Product2AccessoryLocaleOptOut(Product2AccessoryLocaleOptOutPK id) {
		this.id = id;
	}

	public Product2AccessoryLocaleOptOut(Product2AccessoryLocaleOptOutPK id,
			String prodId, String localeOptOut) {
		this.id = id;
		this.prodId = prodId;
		this.localeOptOut = localeOptOut;
	}

	public Product2AccessoryLocaleOptOutPK getId() {
		return this.id;
	}

	public void setId(Product2AccessoryLocaleOptOutPK id) {
		this.id = id;
	}

	public String getProdId() {
		return this.prodId;
	}

	public void setProdId(String prodId) {
		this.prodId = prodId;
	}

	public String getLocaleOptOut() {
		return this.localeOptOut;
	}

	public void setLocaleOptOut(String localeOptOut) {
		this.localeOptOut = localeOptOut;
	}

}
