package com.interwoven.teamsite.nikon.hibernate.beans;

// Generated 18-Oct-2009 14:29:28 by Hibernate Tools 3.2.4.GA

/**
 * Product2ProductMarketingRelated generated by hbm2java
 */
public class Product2ProductMarketingRelated implements java.io.Serializable {

	private Product2ProductMarketingRelatedPK id;
	private String nikonLocale;
	private String prodId;
	private String prodDevCode;
	private String prodProdId;
	private String prodProdDevCode;

	public Product2ProductMarketingRelated() {
	}

	public Product2ProductMarketingRelated(Product2ProductMarketingRelatedPK id) {
		this.id = id;
	}

	public Product2ProductMarketingRelated(
			Product2ProductMarketingRelatedPK id, String nikonLocale,
			String prodId, String prodDevCode, String prodProdId,
			String prodProdDevCode) {
		this.id = id;
		this.nikonLocale = nikonLocale;
		this.prodId = prodId;
		this.prodDevCode = prodDevCode;
		this.prodProdId = prodProdId;
		this.prodProdDevCode = prodProdDevCode;
	}

	public Product2ProductMarketingRelatedPK getId() {
		return this.id;
	}

	public void setId(Product2ProductMarketingRelatedPK id) {
		this.id = id;
	}

	public String getNikonLocale() {
		return this.nikonLocale;
	}

	public void setNikonLocale(String nikonLocale) {
		this.nikonLocale = nikonLocale;
	}

	public String getProdId() {
		return this.prodId;
	}

	public void setProdId(String prodId) {
		this.prodId = prodId;
	}

	public String getProdDevCode() {
		return this.prodDevCode;
	}

	public void setProdDevCode(String prodDevCode) {
		this.prodDevCode = prodDevCode;
	}

	public String getProdProdId() {
		return this.prodProdId;
	}

	public void setProdProdId(String prodProdId) {
		this.prodProdId = prodProdId;
	}

	public String getProdProdDevCode() {
		return this.prodProdDevCode;
	}

	public void setProdProdDevCode(String prodProdDevCode) {
		this.prodProdDevCode = prodProdDevCode;
	}

}
